version: '3'
services:
  app:
    build: .
    container_name: fixed_width_parser
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "python generate_fixed_width.py && python parse_fixed_width.py"
